version: '3.7'

services:
  postgres_local_db:
    image: postgres:latest
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=veryhard123"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=dev"
    networks:
      - default

networks:
  default:
    driver: bridge
